const{chromium}=require('playwright');const fs=require('fs');const base='http://127.0.0.1:3004',out='_local/home-4-evidence';
(async()=>{const b=await chromium.launch({channel:'chrome'}),results=[];for(const width of [1440,390]){const p=await b.newPage({viewport:{width,height:900},hasTouch:width===390,isMobile:width===390});await p.goto(base+'/home-4',{waitUntil:'domcontentloaded'});await p.locator('.h4-intro').waitFor();await p.waitForTimeout(1200);await p.getByRole('button',{name:'Open menu',exact:true}).first().click();await p.waitForTimeout(1800);await p.locator('[aria-controls="eno-group-home"]').click();await p.waitForTimeout(400);const link=p.getByRole('dialog',{name:'Site menu'}).locator('a[href="/home-4"]');results.push({test:'navigation '+width,links:await link.count(),visible:await link.isVisible()});await p.screenshot({path:out+'/navigation-'+width+'.png'});await link.click();await p.waitForTimeout(700);results.push({test:'menu destination '+width,url:p.url(),dialog:await p.getByRole('dialog',{name:'Site menu'}).count()});await p.close();}
const p=await b.newPage({viewport:{width:1440,height:900}});await p.goto(base+'/home-4',{waitUntil:'domcontentloaded'});await p.locator('.h4-intro').waitFor();await p.evaluate(()=>document.fonts.ready);const hrefs=await p.locator('.home-four a[href^="/"]').evaluateAll(es=>[...new Set(es.map(e=>e.getAttribute('href')))]);for(const href of hrefs){const response=await p.request.get(base+href,{timeout:120000});results.push({test:'link '+href,status:response.status()});}
const touch=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await touch.goto(base+'/home-4',{waitUntil:'domcontentloaded'});await touch.locator('.h4-intro').waitFor();await touch.waitForTimeout(1500);const cdp=await touch.context().newCDPSession(touch);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:290,y:600}]});for(let i=1;i<=8;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:290,y:600-i*50}]});await touch.waitForTimeout(35)}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await touch.waitForTimeout(600);results.push({test:'touch swipe',scroll:await touch.evaluate(()=>scrollY)});await touch.close();
await p.evaluate(()=>{document.body.style.zoom='2'});await p.waitForTimeout(1000);results.push({test:'CSS zoom 200%',overflow:await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),note:'CSS zoom plus separate 720x450 viewport reflow; not an OS-level zoom test'});await p.screenshot({path:out+'/zoom-200.png'});await p.evaluate(()=>{document.body.style.zoom=''});
await p.evaluate(async()=>{await document.fonts.load('64px "Piloner Thin"');await document.fonts.load('64px "Playfair Display"');const panel=document.createElement('div');panel.id='h4-glyph-audit';panel.style.cssText='position:fixed;inset:80px 0 0;z-index:99999;background:#f3ede4;color:#14120e;padding:40px';for(const font of ['Piloner Thin','Playfair Display']){const row=document.createElement('div');row.textContent=font+' — 3 4 7 + 210';row.style.cssText=`font-family:"${font}";font-size:64px;line-height:2`;panel.appendChild(row)}document.body.appendChild(panel)});await p.screenshot({path:out+'/glyph-audit.png'});
for(const target of ['http://127.0.0.1:3006/home-4','http://127.0.0.1:3006/api/home-4-preview']){const r=await p.request.get(target);results.push({test:'gate disabled '+target,status:r.status(),hasTitle:(await r.text()).includes('Unpack.')});}const remote=await p.request.get(base+'/home-4',{headers:{host:'www.hathorcruise.com'}});results.push({test:'non-loopback host denied',status:remote.status(),hasContent:(await remote.text()).includes('Unpack.')});const off=await b.newPage();await off.goto('http://127.0.0.1:3006/',{waitUntil:'domcontentloaded'});await off.waitForTimeout(1500);await off.getByRole('button',{name:'Open menu',exact:true}).first().click();results.push({test:'disabled nav absent',links:await off.locator('a[href="/home-4"]').count()});await off.close();
const html=await(await p.request.get(base+'/home-4')).text();results.push({test:'initial HTML',h1:(html.match(/<h1[ >]/g)||[]).length,copy:html.includes('Unpack.'),voyages:html.includes('Aswan to Luxor'),noindex:html.includes('noindex'),canonical:/rel="canonical"/.test(html)});fs.writeFileSync(out+'/acceptance-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));await b.close()})().catch(e=>{console.error(e);process.exit(1)});

