/* Local browser evidence. Never sends a reservation or modifies CMS data. */
const {chromium}=require('playwright');const fs=require('node:fs');
const base=process.env.H4_BASE||'http://127.0.0.1:3004',out='_local/home-4-evidence';
const results=[];const record=(name,data)=>{results.push({name,...data});fs.writeFileSync(out+'/interaction-results.json',JSON.stringify(results,null,2));console.log(name,JSON.stringify(data));};
async function ready(p){await p.goto(base+'/home-4',{waitUntil:'domcontentloaded',timeout:120000});await p.locator('.h4-intro').waitFor({timeout:120000});await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(1500);}
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage({viewport:{width:1440,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await ready(p);
await p.locator('.h4-hero-links a').first().click();await p.waitForTimeout(1000);record('voyage shortcut',await p.locator('#h4-voyages').evaluate(e=>({hash:location.hash,focused:document.activeElement===e,rect:e.getBoundingClientRect().toJSON()})));
await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(1000);await p.locator('.h4-hero-book button').click();await p.waitForTimeout(1000);record('hero booking opens',{dialog:await p.getByRole('dialog').count(),text:(await p.getByRole('dialog').allTextContents()).join(' ').slice(0,400)});await p.screenshot({path:out+'/booking-open.png'});await p.keyboard.press('Escape');
await p.evaluate(()=>scrollTo(0,0));await p.locator('.h4-hero-links a').nth(1).click();await p.waitForTimeout(900);record('closing shortcut',await p.locator('#h4-invitation').evaluate(e=>({hash:location.hash,focused:document.activeElement===e,top:e.getBoundingClientRect().top})));
await p.locator('.h4-close .h4-actions button').click();await p.waitForTimeout(700);record('closing booking opens',{dialog:await p.getByRole('dialog').count()});await p.keyboard.press('Escape');
// Stop selections exercise one common fraction for route, vessel and labels.
for(const i of [0,2,4]){await p.locator('[data-h4-stop]').nth(i).focus();await p.keyboard.press('Enter');await p.waitForTimeout(350);record('map stop '+i,await p.evaluate(()=>{const path=document.querySelector('.h4-course'),v=document.querySelector('.h4-vessel'),L=path.getTotalLength(),offset=parseFloat(path.style.strokeDashoffset),at=path.getPointAtLength(L-offset),m=v.transform.baseVal.consolidate().matrix;return{selected:document.querySelector('[data-h4-stop][aria-pressed=true]').textContent,active:document.querySelector('.h4-stop-detail.h4-active h3').textContent,routeError:Math.hypot(at.x-m.e,at.y-m.f),fraction:(L-offset)/L,transform:v.getAttribute('transform')}}));await p.screenshot({path:out+'/map-'+i+'.png'});}
await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(400);await p.locator('.h4-reading-control button').click();await p.waitForTimeout(500);record('static reading',await p.evaluate(()=>({horizontal:document.querySelector('.home-four').dataset.h4Horizontal,visibleStops:[...document.querySelectorAll('.h4-stop-detail')].filter(e=>getComputedStyle(e).display!=='none').length,videoPaused:document.querySelector('.h4-hero video').paused})));
await p.locator('.h4-reading-control button').click();await p.waitForTimeout(700);
const keyboard=[];await p.locator('.h4-intro .h4-link').focus();for(let i=0;i<22;i++){await p.keyboard.press('Tab');await p.waitForTimeout(180);keyboard.push(await p.evaluate(()=>{const e=document.activeElement,r=e.getBoundingClientRect();return{text:e.textContent.slice(0,45),visible:r.left>=-1&&r.right<=innerWidth+1&&r.top>=0&&r.bottom<=innerHeight,stageScroll:document.querySelector('.h4-stage').scrollLeft}}))}record('keyboard story',{keyboard});
for(const v of [{width:949,height:900},{width:951,height:900},{width:768,height:1024},{width:1024,height:768},{width:720,height:450},{width:1440,height:900}]){await p.setViewportSize(v);await p.waitForTimeout(350);record('resize '+v.width+'x'+v.height,await p.evaluate(()=>({horizontal:document.querySelector('.home-four').dataset.h4Horizontal,overflow:document.documentElement.scrollWidth>innerWidth})));}
await p.evaluate(()=>scrollTo(0,document.body.scrollHeight));await p.waitForTimeout(100);await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(800);record('fast reverse',{heroVisible:await p.locator('.h4-hero-copy').evaluate(e=>parseFloat(getComputedStyle(e).opacity)===1)});
await p.goto(base+'/about');await p.waitForTimeout(1500);record('leave cleanup',await p.evaluate(()=>({homeFour:!!document.querySelector('.home-four'),h4DocumentAttributes:[...document.documentElement.attributes].map(a=>a.name).filter(n=>n.includes('h4')),bodyOverflow:getComputedStyle(document.body).overflowX})));
await p.goBack();await p.locator('.h4-intro').waitFor({timeout:120000});await p.waitForTimeout(800);await p.reload();await p.locator('.h4-intro').waitFor({timeout:120000});record('back and refresh',{h1:await p.locator('h1').allTextContents()});
record('console',{errors});await p.close();
for(const mode of ['reduced','save-data','video-failure','no-js']){const context=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:mode==='reduced'?'reduce':'no-preference',javaScriptEnabled:mode!=='no-js'});const page=await context.newPage();const requests=[];page.on('request',r=>{if(r.url().includes('.mp4'))requests.push(r.url())});if(mode==='save-data')await page.addInitScript(()=>Object.defineProperty(navigator,'connection',{value:{saveData:true,effectiveType:'4g'}}));if(mode==='video-failure')await page.route('**/*.mp4',r=>r.abort());await ready(page);await page.waitForTimeout(1800);record(mode,await page.evaluate(requests=>({h1:document.querySelector('h1').textContent,horizontal:document.querySelector('.home-four').dataset.h4Horizontal,stops:[...document.querySelectorAll('.h4-stop-detail')].filter(e=>getComputedStyle(e).display!=='none').length,videoRequests:requests,poster:document.querySelector('.h4-hero img').naturalWidth,overflow:document.documentElement.scrollWidth>innerWidth}),requests));await page.screenshot({path:out+'/'+mode+'.png',fullPage:mode==='no-js'||mode==='reduced'});if(mode==='video-failure'){await page.touchscreen.tap(95,490);await page.mouse.wheel(0,1400);record('touch scroll',{scroll:await page.evaluate(()=>scrollY)})}await context.close();}
await b.close();})().catch(e=>{console.error(e);process.exitCode=1});
