/**
 * Slot names that have a local copy at /media/hathor/optimized/{name}.webp.
 * Generated by scripts/mirror-supabase-site-images-to-public.mjs — edit that
 * script (or add files to the folder) rather than hand-maintaining this list.
 */
export const LOCAL_OPTIMIZED_SITE_IMAGE_SLOTS: ReadonlySet<string> = new Set([
  "about-hero",
  "cruises-hero",
  "dining-gallery-left",
  "dining-gallery-right",
  "dining-intro-hero",
  "dining-projects-course-1",
  "floating-ig-1",
  "floating-ig-2",
  "floating-ig-3",
  "floating-ig-4",
  "gastronomy-celebration",
  "gastronomy-chef",
  "gastronomy-courses",
  "gastronomy-hero",
  "gastronomy-restaurant",
  "gastronomy-service",
  "gastronomy-table",
  "gastronomy-wine",
  "home-amenities-1",
  "home-amenities-10",
  "home-amenities-11",
  "home-amenities-12",
  "home-amenities-13",
  "home-amenities-14",
  "home-amenities-2",
  "home-amenities-4",
  "home-amenities-5",
  "home-amenities-6",
  "home-amenities-7",
  "home-amenities-8",
  "home-amenities-9",
  "home-call-to-action",
  "home-carousel-royal-3n",
  "home-carousel-royal-4n",
  "home-carousel-royal-7n",
  "home-hero-poster",
  "home-split-courtyard",
  "home-story-craft-large",
  "home-story-dining",
  "home-story-legacy-large",
  "home-story-way-of-life",
  "home-voyage-3n-aswan-luxor",
  "home-voyage-4n-luxor-aswan",
  "home-voyage-7n-roundtrip",
  "home-voyage-nile-majesty",
  "home-wheel-image",
  "home-wheel-stage",
  "moving-tilted-1",
  "moving-tilted-2",
  "moving-tilted-3",
  "moving-tilted-4",
  "moving-tilted-5",
  "room-luxury",
  "room-royal",
  "room-suite",
  "scraped-cabin-1",
  "scraped-luxsuite-1",
  "scraped-luxsuite-2",
  "scraped-luxsuite-3",
  "scraped-luxsuite-4",
  "scraped-luxsuite-5",
  "scraped-luxsuite-6",
  "scraped-royal-1",
  "scraped-royal-2",
  "scraped-royal-3",
  "scraped-royal-4",
  "scraped-royal-5",
  "scraped-royal-6",
  "scraped-royal-7",
  "scraped-royal-8",
  "scraped-suites-hero",
  "scraped-suites-luxury-rooms",
  "scraped-suites-luxury-suites",
  "scraped-suites-royal",
]);

export function isSupabaseStorageUrl(url: string): boolean {
  return url.includes("supabase.co/storage");
}

export function localOptimizedSiteImagePath(name: string): string {
  return `/media/hathor/optimized/${name}.webp`;
}

/**
 * Serve CMS uploads from Vercel (/public) when a mirrored copy exists.
 * Leaves upload/storage backend unchanged — only the URL the browser requests.
 */
export function preferLocalOptimizedSiteImage(name: string, src: string): string {
  const trimmed = src.trim();
  if (!trimmed) return trimmed;
  if (!isSupabaseStorageUrl(trimmed)) return trimmed;
  if (!LOCAL_OPTIMIZED_SITE_IMAGE_SLOTS.has(name)) return trimmed;
  return localOptimizedSiteImagePath(name);
}
