import type { ImageCategory } from "@/lib/image-categories";
import { HATHOR_MEDIA } from "@/lib/hathor-media";

export type SiteImageSlot = {
  name: string;
  altText: string;
  url: string;
  category: ImageCategory;
  pagePath: string;
  displayOrder: number;
};

/** Canonical image slots — seeded to SiteImage and editable in admin → Site Images. */
export const SITE_IMAGE_SLOTS: SiteImageSlot[] = [
  // Homepage (live EX page only)
  {
    name: "home-hero-poster",
    altText: HATHOR_MEDIA.heroHomepageAlt,
    url: HATHOR_MEDIA.heroHomepage,
    category: "hero",
    pagePath: "/",
    displayOrder: 0,
  },
  {
    name: "home-story-craft-large",
    altText: "Ornate interior corridor aboard a luxury Dahabiya",
    url: HATHOR_MEDIA.storyCraftLarge,
    category: "general",
    pagePath: "/",
    displayOrder: 10,
  },
  {
    name: "home-story-legacy-large",
    altText: "Hathor Dahabiya sailing on the Nile",
    url: HATHOR_MEDIA.storyLegacyLarge,
    category: "general",
    pagePath: "/",
    displayOrder: 13,
  },
  {
    name: "home-cinematic-still",
    altText: HATHOR_MEDIA.cinematicStillAlt,
    url: HATHOR_MEDIA.cinematicStill,
    category: "suite",
    pagePath: "/",
    displayOrder: 21,
  },
  {
    name: "home-split-courtyard",
    altText: HATHOR_MEDIA.splitCourtyardAlt,
    url: HATHOR_MEDIA.splitCourtyard,
    category: "landmark",
    pagePath: "/",
    displayOrder: 22,
  },
  {
    name: "home-collage-large",
    altText: "Luxury corridor with chandelier aboard Hathor",
    url: HATHOR_MEDIA.collageLarge,
    category: "general",
    pagePath: "/",
    displayOrder: 41,
  },
  {
    name: "home-collage-small",
    altText: "Marble and mosaic detail aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.collageSmall,
    category: "general",
    pagePath: "/",
    displayOrder: 42,
  },
  {
    name: "home-collage-living",
    altText: "Luxury suite aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.collageLiving,
    category: "suite",
    pagePath: "/",
    displayOrder: 43,
  },
  {
    name: "home-alt-highlights",
    altText: "Ancient landmarks along the Nile",
    url: HATHOR_MEDIA.altHighlights,
    category: "landmark",
    pagePath: "/",
    displayOrder: 62,
  },
  // Homepage “Our Voyages” accordion — dedicated slots (not shared with other pages)
  {
    name: "home-voyage-3n-aswan-luxor",
    altText: "3 Nights / 4 Days Aswan to Luxor voyage aboard Hathor",
    url: HATHOR_MEDIA.heroCruises,
    category: "general",
    pagePath: "/",
    displayOrder: 70,
  },
  {
    name: "home-voyage-4n-luxor-aswan",
    altText: "4 Nights / 5 Days Luxor to Aswan voyage aboard Hathor",
    url: HATHOR_MEDIA.splitCourtyard,
    category: "general",
    pagePath: "/",
    displayOrder: 71,
  },
  {
    name: "home-voyage-7n-roundtrip",
    altText: "7 Nights / 8 Days Luxor to Aswan to Luxor voyage aboard Hathor",
    url: HATHOR_MEDIA.storyLegacyLarge,
    category: "general",
    pagePath: "/",
    displayOrder: 72,
  },
  {
    name: "home-voyage-nile-majesty",
    altText: "Nile Majesty voyage aboard Hathor",
    url: HATHOR_MEDIA.collageLiving,
    category: "general",
    pagePath: "/",
    displayOrder: 73,
  },
  // Shared accommodations
  {
    name: "room-luxury",
    altText: "Luxury cabin aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.luxuryRoom,
    category: "room",
    pagePath: "/rooms",
    displayOrder: 0,
  },
  {
    name: "room-suite",
    altText: "Luxury suite aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.luxurySuite,
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 1,
  },
  {
    name: "room-royal",
    altText: "Royal suite aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.royalSuite,
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 2,
  },
  {
    name: "charter",
    altText: "Private charter aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.charter,
    category: "general",
    pagePath: "/charter",
    displayOrder: 0,
  },
  // Page heroes
  {
    name: "cruises-hero",
    altText: "Luxury Dahabiya cruise on the Nile",
    url: HATHOR_MEDIA.heroCruises,
    category: "hero",
    pagePath: "/cruises",
    displayOrder: 0,
  },
  {
    name: "about-hero",
    altText: "Hathor Dahabiya sailing on the Nile",
    url: HATHOR_MEDIA.about,
    category: "hero",
    pagePath: "/about",
    displayOrder: 0,
  },
  {
    name: "gastronomy-hero",
    altText: "Gourmet dining aboard Hathor Dahabiya with Nile views",
    url: HATHOR_MEDIA.dining,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 0,
  },
  {
    name: "gastronomy-restaurant",
    altText: "Hathor Dahabiya restaurant interior",
    url: HATHOR_MEDIA.restaurant,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 1,
  },
  {
    name: "wellness-hero",
    altText: "Seneb Spa wellness aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.wellness,
    category: "spa",
    pagePath: "/wellness",
    displayOrder: 0,
  },
  {
    name: "wellness-fitness",
    altText: "Fitness and active wellness aboard Hathor",
    url: HATHOR_MEDIA.fitness,
    category: "spa",
    pagePath: "/wellness",
    displayOrder: 1,
  },
  {
    name: "highlights-hero",
    altText: "Dahabiya sailing past ancient Egyptian monuments",
    url: HATHOR_MEDIA.highlights,
    category: "landmark",
    pagePath: "/highlights",
    displayOrder: 0,
  },
  {
    name: "highlights-lifestyle",
    altText: "Scenic Nile views from Hathor Dahabiya",
    url: HATHOR_MEDIA.lifestyle,
    category: "landmark",
    pagePath: "/highlights",
    displayOrder: 1,
  },
  {
    name: "landmark-obelisk",
    altText: "Unfinished Obelisk, Aswan",
    url: HATHOR_MEDIA.obelisk,
    category: "landmark",
    pagePath: "/highlights",
    displayOrder: 2,
  },
  {
    name: "landmark-hatshepsut",
    altText: "Temple of Hatshepsut",
    url: HATHOR_MEDIA.templeHatshepsut,
    category: "landmark",
    pagePath: "/highlights",
    displayOrder: 3,
  },
  {
    name: "landmark-valley-kings",
    altText: "Valley of the Kings, Luxor",
    url: HATHOR_MEDIA.valleyOfKings,
    category: "landmark",
    pagePath: "/highlights",
    displayOrder: 4,
  },
  {
    name: "charter-hero",
    altText: "Private charter on the Hathor Dahabiya",
    url: HATHOR_MEDIA.heroCharter,
    category: "hero",
    pagePath: "/charter",
    displayOrder: 0,
  },
  {
    name: "contact-hero",
    altText: "Hathor Dahabiya on the Nile",
    url: HATHOR_MEDIA.heroContact,
    category: "hero",
    pagePath: "/contact",
    displayOrder: 0,
  },
  {
    name: "blog-hero",
    altText: "Hathor Dahabiya blog — stories from the Nile",
    url: HATHOR_MEDIA.heroBlog,
    category: "general",
    pagePath: "/blogs",
    displayOrder: 0,
  },
  {
    name: "about-dining",
    altText: "Fine dining aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.dining,
    category: "dining",
    pagePath: "/about",
    displayOrder: 1,
  },
  // Scraped from hathorcruise.com accommodation pages (Jul 2026)
  {
    name: "scraped-suites-hero",
    altText: "Cabins and suites aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/suites-hero.jpg",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 10,
  },
  {
    name: "scraped-suites-luxury-rooms",
    altText: "Luxury Rooms aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/suites-luxury-rooms.webp",
    category: "room",
    pagePath: "/rooms",
    displayOrder: 11,
  },
  {
    name: "scraped-suites-luxury-suites",
    altText: "Luxury Suites aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/suites-luxury-suites.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 12,
  },
  {
    name: "scraped-suites-royal",
    altText: "Luxury Royal Suites aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/suites-royal.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 13,
  },
  {
    name: "scraped-luxsuite-1",
    altText: "Luxury suite interior aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/luxsuite-1.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 14,
  },
  {
    name: "scraped-luxsuite-2",
    altText: "Luxury suite bedroom aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/luxsuite-2.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 15,
  },
  {
    name: "scraped-luxsuite-3",
    altText: "Luxury suite lounge aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/luxsuite-3.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 16,
  },
  {
    name: "scraped-luxsuite-4",
    altText: "Luxury suite bathroom aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/luxsuite-4.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 17,
  },
  {
    name: "scraped-luxsuite-5",
    altText: "Luxury suite bedroom with Nile light",
    url: "/media/hathor/scraped/luxsuite-5.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 18,
  },
  {
    name: "scraped-luxsuite-6",
    altText: "Accessible Hathor Suite aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/luxsuite-6.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 19,
  },
  {
    name: "scraped-royal-1",
    altText: "Royal suite aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/royal-1.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 10,
  },
  {
    name: "scraped-royal-2",
    altText: "Royal suite bedroom aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/royal-2.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 11,
  },
  {
    name: "scraped-royal-3",
    altText: "Royal suite jacuzzi aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/royal-3.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 12,
  },
  {
    name: "scraped-royal-4",
    altText: "Sunset Nile view from a Royal Suite",
    url: "/media/hathor/scraped/royal-4.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 13,
  },
  {
    name: "scraped-royal-5",
    altText: "Royal suite living space aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/royal-5.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 14,
  },
  {
    name: "scraped-royal-6",
    altText: "Royal suite lounge aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/royal-6.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 15,
  },
  {
    name: "scraped-royal-7",
    altText: "Royal suite bathroom with Nile view",
    url: "/media/hathor/scraped/royal-7.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 16,
  },
  {
    name: "scraped-royal-8",
    altText: "Breakfast in a Royal Suite aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/royal-8.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 17,
  },
  {
    name: "scraped-cabin-1",
    altText: "Luxury King Bed cabin aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/cabin-1.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 10,
  },
  {
    name: "scraped-cabin-2",
    altText: "Luxury cabin interior aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/cabin-2.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 11,
  },
  {
    name: "scraped-cabin-3",
    altText: "Master bedroom cabin aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/cabin-3.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 12,
  },
  {
    name: "scraped-cabin-4",
    altText: "Luxury Nile cruise room aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/cabin-4.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 13,
  },
  {
    name: "scraped-cabin-5",
    altText: "Luxury Twin Bed cabin aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/cabin-5.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 14,
  },
  {
    name: "scraped-cabin-6",
    altText: "Twin cabin with panoramic Nile window",
    url: "/media/hathor/scraped/cabin-6.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 15,
  },
  {
    name: "scraped-cabin-7",
    altText: "Luxury cabin bathroom aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/cabin-7.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 16,
  },
  {
    name: "scraped-cabin-8",
    altText: "Cabin bathroom with Nile view",
    url: "/media/hathor/scraped/cabin-8.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 17,
  },
];

export type SiteImageName = (typeof SITE_IMAGE_SLOTS)[number]["name"];

const SLOT_BY_NAME = new Map(SITE_IMAGE_SLOTS.map((slot) => [slot.name, slot]));

export function getSiteImageSlot(name: string): SiteImageSlot | undefined {
  return SLOT_BY_NAME.get(name);
}

export function getDefaultSiteImage(name: string): { src: string; alt: string } {
  const slot = getSiteImageSlot(name);
  if (!slot) {
    return { src: HATHOR_MEDIA.heroHomepage, alt: "Hathor Dahabiya" };
  }
  return { src: slot.url, alt: slot.altText };
}
