import type { ImageCategory } from "@/lib/image-categories";
import { GASTRONOMY_DINING_MEDIA } from "@/lib/gastronomy-dining-media";
import { HATHOR_MEDIA } from "@/lib/hathor-media";

export type SiteImageSlot = {
  name: string;
  altText: string;
  url: string;
  category: ImageCategory;
  pagePath: string;
  displayOrder: number;
};

/** Canonical image slots — seeded to SiteImage and editable in admin → Site Images. */
export const SITE_IMAGE_SLOTS: SiteImageSlot[] = [
  // Homepage (live EX page only)
  {
    name: "home-hero-poster",
    altText: HATHOR_MEDIA.heroHomepageAlt,
    url: HATHOR_MEDIA.heroHomepage,
    category: "hero",
    pagePath: "/",
    displayOrder: 0,
  },
  {
    name: "home-story-craft-large",
    altText: "Ornate interior corridor aboard a luxury Dahabiya",
    url: HATHOR_MEDIA.storyCraftLarge,
    category: "general",
    pagePath: "/",
    displayOrder: 10,
  },
  {
    name: "home-story-legacy-large",
    altText: "Hathor Dahabiya sailing on the Nile",
    url: HATHOR_MEDIA.storyLegacyLarge,
    category: "general",
    pagePath: "/",
    displayOrder: 13,
  },
  {
    name: "home-story-way-of-life",
    altText: "Guests enjoying a Nile sunset moment aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.storyWayOfLife,
    category: "general",
    pagePath: "/",
    displayOrder: 14,
  },
  {
    name: "home-story-dining",
    altText: "Fine dining aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.storyDining,
    category: "dining",
    pagePath: "/",
    displayOrder: 15,
  },
  {
    name: "home-cinematic-still",
    altText: HATHOR_MEDIA.cinematicStillAlt,
    url: HATHOR_MEDIA.cinematicStill,
    category: "suite",
    pagePath: "/",
    displayOrder: 21,
  },
  {
    name: "home-split-courtyard",
    altText: HATHOR_MEDIA.splitCourtyardAlt,
    url: HATHOR_MEDIA.splitCourtyard,
    category: "landmark",
    pagePath: "/",
    displayOrder: 22,
  },
  {
    name: "home-collage-living",
    altText: "Luxury suite aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.collageLiving,
    category: "suite",
    pagePath: "/",
    displayOrder: 43,
  },
  {
    name: "home-alt-highlights",
    altText: "Ancient landmarks along the Nile",
    url: HATHOR_MEDIA.altHighlights,
    category: "landmark",
    pagePath: "/",
    displayOrder: 62,
  },
  {
    name: "home-call-to-action",
    altText: "Call to action — Hathor Dahabiya on the Nile at golden hour",
    url: HATHOR_MEDIA.storyLegacyLarge,
    category: "hero",
    pagePath: "/",
    displayOrder: 70,
  },
  {
    name: "home-wheel-stage",
    altText: HATHOR_MEDIA.wheelStageAlt,
    url: HATHOR_MEDIA.wheelStage,
    category: "hero",
    pagePath: "/",
    displayOrder: 71,
  },
  {
    name: "home-wheel-image",
    altText: "Wheel portal — Hathor Dahabiya on the Nile at golden hour",
    url: HATHOR_MEDIA.wheelBack,
    category: "hero",
    pagePath: "/",
    displayOrder: 72,
  },
  // Homepage “Our Voyages” accordion — dedicated slots (Admin tab: Our Voyages)
  {
    name: "home-voyage-3n-aswan-luxor",
    altText: "3 Nights / 4 Days Aswan to Luxor voyage aboard Hathor",
    url: HATHOR_MEDIA.heroCruises,
    category: "general",
    pagePath: "/#our-voyages",
    displayOrder: 0,
  },
  {
    name: "home-voyage-4n-luxor-aswan",
    altText: "4 Nights / 5 Days Luxor to Aswan voyage aboard Hathor",
    url: HATHOR_MEDIA.splitCourtyard,
    category: "general",
    pagePath: "/#our-voyages",
    displayOrder: 1,
  },
  {
    name: "home-voyage-7n-roundtrip",
    altText: "7 Nights / 8 Days Luxor to Aswan to Luxor voyage aboard Hathor",
    url: HATHOR_MEDIA.storyLegacyLarge,
    category: "general",
    pagePath: "/#our-voyages",
    displayOrder: 2,
  },
  {
    name: "home-voyage-nile-majesty",
    altText: "Nile Majesty voyage aboard Hathor",
    url: HATHOR_MEDIA.collageLiving,
    category: "general",
    pagePath: "/#our-voyages",
    displayOrder: 3,
  },
  // Shared accommodations
  {
    name: "room-luxury",
    altText: "Luxury cabin aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.luxuryRoom,
    category: "room",
    pagePath: "/rooms",
    displayOrder: 0,
  },
  {
    name: "room-suite",
    altText: "Luxury suite aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.luxurySuite,
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 1,
  },
  {
    name: "room-royal",
    altText: "Royal suite aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.royalSuite,
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 2,
  },
  {
    name: "charter",
    altText: "Private charter aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.charter,
    category: "general",
    pagePath: "/charter",
    displayOrder: 0,
  },
  // Page heroes
  {
    name: "cruises-hero",
    altText: "Luxury Dahabiya cruise on the Nile",
    url: HATHOR_MEDIA.heroCruises,
    category: "hero",
    pagePath: "/cruises",
    displayOrder: 0,
  },
  {
    name: "about-hero",
    altText: "Hathor Dahabiya sailing on the Nile",
    url: HATHOR_MEDIA.about,
    category: "hero",
    pagePath: "/about",
    displayOrder: 0,
  },
  {
    name: "gastronomy-hero",
    altText: "Candlelit private dining table aboard Hathor Dahabiya",
    url: GASTRONOMY_DINING_MEDIA.hero,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 0,
  },
  {
    name: "gastronomy-restaurant",
    altText: "Fine dining table detail aboard Hathor Dahabiya",
    url: GASTRONOMY_DINING_MEDIA.experience,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 1,
  },
  {
    name: "gastronomy-table",
    altText: "Long table set for a private party aboard Hathor",
    url: GASTRONOMY_DINING_MEDIA.table,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 2,
  },
  {
    name: "gastronomy-courses",
    altText: "Tasting menu courses aboard Hathor Dahabiya",
    url: GASTRONOMY_DINING_MEDIA.courses,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 3,
  },
  {
    name: "gastronomy-wine",
    altText: "Wine and crystal in warm light aboard Hathor",
    url: GASTRONOMY_DINING_MEDIA.wine,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 4,
  },
  {
    name: "gastronomy-chef",
    altText: "Private chef plating aboard Hathor Dahabiya",
    url: GASTRONOMY_DINING_MEDIA.chef,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 5,
  },
  {
    name: "gastronomy-service",
    altText: "Dedicated service at the dining table aboard Hathor",
    url: GASTRONOMY_DINING_MEDIA.service,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 6,
  },
  {
    name: "gastronomy-celebration",
    altText: "Evening celebration dining aboard Hathor Dahabiya",
    url: GASTRONOMY_DINING_MEDIA.celebration,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 7,
  },
  {
    name: "gastronomy-plate-1",
    altText: "Gastronomy — signature tasting plate",
    url: GASTRONOMY_DINING_MEDIA.plate1,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 10,
  },
  {
    name: "gastronomy-plate-2",
    altText: "Gastronomy — dessert plate",
    url: GASTRONOMY_DINING_MEDIA.plate2,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 11,
  },
  {
    name: "gastronomy-plate-3",
    altText: "Gastronomy — seafood plate",
    url: GASTRONOMY_DINING_MEDIA.plate3,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 12,
  },
  {
    name: "gastronomy-plate-4",
    altText: "Gastronomy — seasonal plate",
    url: GASTRONOMY_DINING_MEDIA.plate4,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 13,
  },
  {
    name: "gastronomy-plate-5",
    altText: "Gastronomy — gallery plate one",
    url: GASTRONOMY_DINING_MEDIA.plate5,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 14,
  },
  {
    name: "gastronomy-plate-6",
    altText: "Gastronomy — gallery plate two",
    url: GASTRONOMY_DINING_MEDIA.plate6,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 15,
  },
  {
    name: "gastronomy-plate-7",
    altText: "Gastronomy — gallery plate three",
    url: GASTRONOMY_DINING_MEDIA.plate7,
    category: "dining",
    pagePath: "/gastronomy",
    displayOrder: 16,
  },
  {
    name: "wellness-hero",
    altText: "Seneb Spa wellness aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.wellness,
    category: "spa",
    pagePath: "/wellness",
    displayOrder: 0,
  },
  {
    name: "wellness-fitness",
    altText: "Fitness and active wellness aboard Hathor",
    url: HATHOR_MEDIA.fitness,
    category: "spa",
    pagePath: "/wellness",
    displayOrder: 1,
  },
  {
    name: "highlights-hero",
    altText: "Dahabiya sailing past ancient Egyptian monuments",
    url: HATHOR_MEDIA.highlights,
    category: "landmark",
    pagePath: "/highlights",
    displayOrder: 0,
  },
  {
    name: "highlights-lifestyle",
    altText: "Scenic Nile views from Hathor Dahabiya",
    url: HATHOR_MEDIA.lifestyle,
    category: "landmark",
    pagePath: "/highlights",
    displayOrder: 1,
  },
  {
    name: "landmark-obelisk",
    altText: "Unfinished Obelisk, Aswan",
    url: HATHOR_MEDIA.obelisk,
    category: "landmark",
    pagePath: "/highlights",
    displayOrder: 2,
  },
  {
    name: "landmark-hatshepsut",
    altText: "Temple of Hatshepsut",
    url: HATHOR_MEDIA.templeHatshepsut,
    category: "landmark",
    pagePath: "/highlights",
    displayOrder: 3,
  },
  {
    name: "landmark-valley-kings",
    altText: "Valley of the Kings, Luxor",
    url: HATHOR_MEDIA.valleyOfKings,
    category: "landmark",
    pagePath: "/highlights",
    displayOrder: 4,
  },
  {
    name: "charter-hero",
    altText: "Private charter on the Hathor Dahabiya",
    url: HATHOR_MEDIA.heroCharter,
    category: "hero",
    pagePath: "/charter",
    displayOrder: 0,
  },
  {
    name: "charter-privacy",
    altText: "Private sun deck reserved exclusively for your party",
    url: HATHOR_MEDIA.heroCharter,
    category: "general",
    pagePath: "/charter",
    displayOrder: 1,
  },
  {
    name: "charter-service",
    altText: "Dedicated hospitality and service aboard Hathor",
    url: HATHOR_MEDIA.splitService,
    category: "general",
    pagePath: "/charter",
    displayOrder: 2,
  },
  {
    name: "charter-rhythm",
    altText: "Unhurried sailing rhythm along the Nile",
    url: HATHOR_MEDIA.about,
    category: "general",
    pagePath: "/charter",
    displayOrder: 3,
  },
  {
    name: "charter-itinerary",
    altText: "A voyage composed around your itinerary",
    url: HATHOR_MEDIA.storyLegacyLarge,
    category: "general",
    pagePath: "/charter",
    displayOrder: 4,
  },
  {
    name: "contact-hero",
    altText: "Hathor Dahabiya on the Nile",
    url: HATHOR_MEDIA.heroContact,
    category: "hero",
    pagePath: "/contact",
    displayOrder: 0,
  },
  {
    name: "blog-hero",
    altText: "Hathor Dahabiya blog — stories from the Nile",
    url: HATHOR_MEDIA.heroBlog,
    category: "general",
    pagePath: "/blogs",
    displayOrder: 0,
  },
  {
    name: "about-dining",
    altText: "Fine dining aboard Hathor Dahabiya",
    url: HATHOR_MEDIA.dining,
    category: "dining",
    pagePath: "/about",
    displayOrder: 1,
  },
  // Scraped from hathorcruise.com accommodation pages (Jul 2026)
  {
    name: "scraped-suites-hero",
    altText: "Cabins and suites aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/suites-hero.jpg",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 10,
  },
  {
    name: "scraped-suites-luxury-rooms",
    altText: "Luxury Rooms aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/suites-luxury-rooms.webp",
    category: "room",
    pagePath: "/rooms",
    displayOrder: 11,
  },
  {
    name: "scraped-suites-luxury-suites",
    altText: "Luxury Suites aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/suites-luxury-suites.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 12,
  },
  {
    name: "scraped-suites-royal",
    altText: "Luxury Royal Suites aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/suites-royal.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 13,
  },
  {
    name: "scraped-luxsuite-1",
    altText: "Luxury suite interior aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/luxsuite-1.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 14,
  },
  {
    name: "scraped-luxsuite-2",
    altText: "Luxury suite bedroom aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/luxsuite-2.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 15,
  },
  {
    name: "scraped-luxsuite-3",
    altText: "Luxury suite lounge aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/luxsuite-3.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 16,
  },
  {
    name: "scraped-luxsuite-4",
    altText: "Luxury suite bathroom aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/luxsuite-4.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 17,
  },
  {
    name: "scraped-luxsuite-5",
    altText: "Luxury suite bedroom with Nile light",
    url: "/media/hathor/scraped/luxsuite-5.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 18,
  },
  {
    name: "scraped-luxsuite-6",
    altText: "Accessible Hathor Suite aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/luxsuite-6.webp",
    category: "suite",
    pagePath: "/rooms",
    displayOrder: 19,
  },
  {
    name: "scraped-royal-1",
    altText: "Royal suite aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/royal-1.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 10,
  },
  {
    name: "scraped-royal-2",
    altText: "Royal suite bedroom aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/royal-2.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 11,
  },
  {
    name: "scraped-royal-3",
    altText: "Royal suite jacuzzi aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/royal-3.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 12,
  },
  {
    name: "scraped-royal-4",
    altText: "Sunset Nile view from a Royal Suite",
    url: "/media/hathor/scraped/royal-4.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 13,
  },
  {
    name: "scraped-royal-5",
    altText: "Royal suite living space aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/royal-5.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 14,
  },
  {
    name: "scraped-royal-6",
    altText: "Royal suite lounge aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/royal-6.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 15,
  },
  {
    name: "scraped-royal-7",
    altText: "Royal suite bathroom with Nile view",
    url: "/media/hathor/scraped/royal-7.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 16,
  },
  {
    name: "scraped-royal-8",
    altText: "Breakfast in a Royal Suite aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/royal-8.webp",
    category: "suite",
    pagePath: "/Luxury-Royal-Suites-Nile-Dahabiya-Cruise",
    displayOrder: 17,
  },
  {
    name: "scraped-cabin-1",
    altText: "Luxury King Bed cabin aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/cabin-1.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 10,
  },
  {
    name: "scraped-cabin-2",
    altText: "Luxury cabin interior aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/cabin-2.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 11,
  },
  {
    name: "scraped-cabin-3",
    altText: "Master bedroom cabin aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/cabin-3.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 12,
  },
  {
    name: "scraped-cabin-4",
    altText: "Luxury Nile cruise room aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/cabin-4.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 13,
  },
  {
    name: "scraped-cabin-5",
    altText: "Luxury Twin Bed cabin aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/cabin-5.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 14,
  },
  {
    name: "scraped-cabin-6",
    altText: "Twin cabin with panoramic Nile window",
    url: "/media/hathor/scraped/cabin-6.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 15,
  },
  {
    name: "scraped-cabin-7",
    altText: "Luxury cabin bathroom aboard Hathor Dahabiya",
    url: "/media/hathor/scraped/cabin-7.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 16,
  },
  {
    name: "scraped-cabin-8",
    altText: "Cabin bathroom with Nile view",
    url: "/media/hathor/scraped/cabin-8.webp",
    category: "room",
    pagePath: "/luxury-cabins-Nile-Cruise",
    displayOrder: 17,
  },
  // Floating Instagram bubbles — Sail with Hathor only (independent of other page photos)
  {
    name: "floating-ig-1",
    altText: "Hathor Instagram float — lounge",
    url: HATHOR_MEDIA.collageLiving,
    category: "general",
    pagePath: "/#floating-ig",
    displayOrder: 1,
  },
  {
    name: "floating-ig-2",
    altText: "Hathor Instagram float — Nile highlights",
    url: HATHOR_MEDIA.altHighlights,
    category: "general",
    pagePath: "/#floating-ig",
    displayOrder: 2,
  },
  {
    name: "floating-ig-3",
    altText: "Hathor Instagram float — dining",
    url: HATHOR_MEDIA.restaurant,
    category: "general",
    pagePath: "/#floating-ig",
    displayOrder: 3,
  },
  {
    name: "floating-ig-4",
    altText: "Hathor Instagram float — suite",
    url: HATHOR_MEDIA.cinematicStill,
    category: "general",
    pagePath: "/#floating-ig",
    displayOrder: 4,
  },
  // Moving tilted cards — homepage gallery only (independent of all other photos)
  {
    name: "moving-tilted-1",
    altText: "Moving tilted card — luxury lounge aboard Hathor",
    url: HATHOR_MEDIA.collageLiving,
    category: "general",
    pagePath: "/#moving-tilted-cards",
    displayOrder: 1,
  },
  {
    name: "moving-tilted-2",
    altText: "Moving tilted card — Nile cruise highlights",
    url: HATHOR_MEDIA.altHighlights,
    category: "general",
    pagePath: "/#moving-tilted-cards",
    displayOrder: 2,
  },
  {
    name: "moving-tilted-3",
    altText: "Moving tilted card — gastronomy on the Nile",
    url: HATHOR_MEDIA.restaurant,
    category: "general",
    pagePath: "/#moving-tilted-cards",
    displayOrder: 3,
  },
  {
    name: "moving-tilted-4",
    altText: "Moving tilted card — wellness aboard Hathor",
    url: HATHOR_MEDIA.wellness,
    category: "general",
    pagePath: "/#moving-tilted-cards",
    displayOrder: 4,
  },
  {
    name: "moving-tilted-5",
    altText: "Moving tilted card — suite interior aboard Hathor",
    url: HATHOR_MEDIA.cinematicStill,
    category: "general",
    pagePath: "/#moving-tilted-cards",
    displayOrder: 5,
  },
];

export type SiteImageName = (typeof SITE_IMAGE_SLOTS)[number]["name"];

const SLOT_BY_NAME = new Map(SITE_IMAGE_SLOTS.map((slot) => [slot.name, slot]));

export function getSiteImageSlot(name: string): SiteImageSlot | undefined {
  return SLOT_BY_NAME.get(name);
}

export function getDefaultSiteImage(name: string): { src: string; alt: string } {
  const slot = getSiteImageSlot(name);
  if (!slot) {
    return { src: HATHOR_MEDIA.heroHomepage, alt: "Hathor Dahabiya" };
  }
  return { src: slot.url, alt: slot.altText };
}
