UPDATE "SiteImage" AS s
SET url = v.url
FROM (
  VALUES
  ('home-hero-poster', '/media/hathor/home-hero-poster.webp'),
  ('home-post-hero-media', '/media/hathor/home-post-hero-media.webp'),
  ('home-story-craft-large', '/media/hathor/home-story-craft-large.webp'),
  ('home-story-craft-small', '/media/hathor/home-story-craft-small.webp'),
  ('home-story-transform', '/media/hathor/home-story-transform.webp'),
  ('home-story-legacy-large', '/media/hathor/home-story-legacy-large.webp'),
  ('home-story-legacy-small', '/media/hathor/home-story-legacy-small.webp'),
  ('home-cinematic-video', '/media/hathor/home-cinematic-video.webp'),
  ('home-cinematic-still', '/media/hathor/home-cinematic-still.webp'),
  ('home-split-courtyard', '/media/hathor/home-split-courtyard.webp'),
  ('home-split-service', '/media/hathor/home-split-service.webp'),
  ('home-split-interiors', '/media/hathor/home-split-interiors.webp'),
  ('home-split-venue', '/media/hathor/home-split-venue.webp'),
  ('home-collage-bg', '/media/hathor/home-collage-bg.webp'),
  ('home-collage-large', '/media/hathor/home-collage-large.webp'),
  ('home-collage-small', '/media/hathor/home-collage-small.webp'),
  ('home-collage-living', '/media/hathor/home-collage-living.webp'),
  ('home-residences-kitchen', '/media/hathor/home-residences-kitchen.webp'),
  ('home-residences-lounge', '/media/hathor/home-residences-lounge.webp'),
  ('home-residences-rooftop', '/media/hathor/home-residences-rooftop.webp'),
  ('home-sketch-boat', '/media/hathor/home-sketch-boat.webp'),
  ('home-alt-dining', '/media/hathor/home-alt-dining.webp'),
  ('home-alt-wellness', '/media/hathor/home-alt-wellness.webp'),
  ('home-alt-highlights', '/media/hathor/home-alt-highlights.webp'),
  ('home-testimonials-bg', '/media/hathor/home-testimonials-bg.webp'),
  ('room-luxury', '/media/hathor/room-luxury.webp'),
  ('room-suite', '/media/hathor/room-suite.webp'),
  ('room-royal', '/media/hathor/room-royal.webp'),
  ('charter', '/media/hathor/charter.webp'),
  ('cruises-hero', '/media/hathor/cruises-hero.webp'),
  ('about-hero', '/media/hathor/about-hero.webp'),
  ('gastronomy-hero', '/media/hathor/gastronomy-hero.webp'),
  ('gastronomy-restaurant', '/media/hathor/gastronomy-restaurant.webp'),
  ('wellness-hero', '/media/hathor/wellness-hero.webp'),
  ('wellness-fitness', '/media/hathor/wellness-fitness.webp'),
  ('highlights-hero', '/media/hathor/highlights-hero.webp'),
  ('highlights-lifestyle', '/media/hathor/highlights-lifestyle.webp'),
  ('landmark-obelisk', '/media/hathor/landmark-obelisk.webp'),
  ('landmark-hatshepsut', '/media/hathor/landmark-hatshepsut.webp'),
  ('landmark-valley-kings', '/media/hathor/landmark-valley-kings.webp'),
  ('charter-hero', '/media/hathor/charter-hero.webp'),
  ('contact-hero', '/media/hathor/contact-hero.webp'),
  ('blog-hero', '/media/hathor/blog-hero.webp'),
  ('about-dining', '/media/hathor/about-dining.webp'),
  ('legacy-cabin', '/media/hathor/legacy-cabin.webp'),
  ('legacy-suite', '/media/hathor/legacy-suite.webp'),
  ('legacy-royal', '/media/hathor/legacy-royal.webp'),
  ('legacy-interior', '/media/hathor/legacy-interior.webp')
) AS v(name, url)
WHERE s.name = v.name;